### ISSUE TITLE
Differentiate or Merge Stage 1 and 2

### ISSUE THREAD

**Issue by CaptainEmerson** [barik/survey-chp-ds4se#15]
It seems that Stages 1 and 2 are about the same topic: Getting more data to
compose a more well thought survey (btw, doing interviews is not the only way
to do it well, maybe you want to mention other methods that can be used to
reach the same goal). I would encourage you to merge the two stages into one.

**Comment by barik** [comment]
> It seems that Stages 1 and 2 are about the same topic: Getting more data to
compose a more well thought survey.

Re-reading the chapter, I don't think this criticism is actually right. Stage 1 only really yields a participant pool from which to then do the interviews. And there's a logical breakpoint since one must wait between the two stages 1.
